apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-command
  namespace: mytestcommand
spec:
  project: 'akzure'
  source:
    repoURL: 'oci://akzure.azurecr.io/helm/helm-command'    # URL del repo del chart
    targetRevision: '0.1.0'                       # Versión del chart
    chart: 'helm-command'                             # Nombre del chart
    helm:
      valueFiles:                                 # Archivos de valores adicionales
        - https://akzureops@dev.azure.com/akzureops/akzuredevops/_git/helm-command/values.yaml  # URL del archivo values.yaml
  destination:
    server: 'https://api.kube2.okd.piensoluegoinstalo.com:6443'
    namespace: 'mytestcommand'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
