trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, Kubernetes!
            displayName: 'Run a one-line script'
          
          - task: Docker@2
            inputs:
              containerRegistry: 'serviceConnectionAkzureRegistry'
              repository: 'akzure.azurecr.io/helm'
              command: 'login'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'eb516520-7a5f-4868-b276-087b4424d83a'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az acr login --name akzure


          - script: |
              docker info
            displayName: 'Verify Docker Login'
            continueOnError: false


          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - script: |
              export HELM_EXPERIMENTAL_OCI=1
            displayName: 'set HELM_EXPERIMENTAL_OCI=1'

          - script: |
              helm pull oci://akzure.azurecr.io/helm/helm-command --version 0.1.0

          - script: |
              ls -la
            displayName: 'ls -la'

          - script: |
              helm repo add my-repo https://akzure.azurecr.io/helm/v1/repo
              helm repo list
            displayName: 'Helm repo list'