trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, Kubernetes!
            displayName: 'Run a one-line script'
          
          - task: Docker@2
            inputs:
              containerRegistry: 'serviceConnectionAkzureRegistry'
              repository: 'akzure.azurecr.io/helm'
              command: 'login'

          - script: |
              docker info
            displayName: 'Verify Docker Login'
            continueOnError: false


          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - script: |
              ls -la
            displayName: 'ls -la'

          - script: |
              helm pull oci://akzure.azurecr.io/helm/helm-command --version .1.0

          - script: |
              helm repo add my-repo https://akzure.azurecr.io/helm/v1/repo
              helm repo list
            displayName: 'Helm repo list'