trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, Kubernetes!
            displayName: 'Run a one-line script'

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - script: |
              ls -la
            displayName: 'ls -la'

          - script: |
              helm init --client-only
              helm repo add stable https://kubernetes-charts.storage.googleapis.com/
              helm repo update
            displayName: 'Install Helm'