trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, Kubernetes!
            displayName: 'Run a one-line script'

          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - script: |
              ls -la
            displayName: 'ls -la'

          - script: |
              helm repo add my-repo oci://mi-registro.azurecr.io/helm
              helm repo update
              helm repo list
            displayName: 'Install Helm'