trigger:
  - main

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: echo Hello, Kubernetes!
            displayName: 'Run a one-line script'
          
          - task: Docker@2
            inputs:
              containerRegistry: 'serviceConnectionAkzureRegistry'
              repository: 'akzure.azurecr.io/helm'
              command: 'login'

          - task: Bash@3
            displayName: Azure login
            inputs:
              targetType: "inline"
              script: az login


          - script: |
              docker info
            displayName: 'Verify Docker Login'
            continueOnError: false


          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'

          - script: |
              export HELM_EXPERIMENTAL_OCI=1
            displayName: 'set HELM_EXPERIMENTAL_OCI=1'

          - script: |
              helm pull oci://akzure.azurecr.io/helm/helm-command --version 0.1.0

          - script: |
              ls -la
            displayName: 'ls -la'

          - script: |
              az acr repository list --name akzure
              helm repo list
            displayName: 'Helm repo list'