kind: Secret
apiVersion: v1
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL3JlZ2lzdHJ5LnBpZW5zb2x1ZWdvaW5zdGFsby5jb206NTAwMCI6eyJ1c2VybmFtZSI6ImFrYXJvbnRlIiwicGFzc3dvcmQiOiJtb25kYXJpejEwIiwiZW1haWwiOiJha2Fyb250ZUBob3RtYWlsLmNvbSIsImF1dGgiOiJZV3RoY205dWRHVTZiVzl1WkdGeWFYb3hNQT09In19fQ==
type: kubernetes.io/dockerconfigjson